apiVersion: v1
kind: Service
metadata:
  labels:
    app: hs-box-office
  name: hs-box-office
spec:
  type: NodePort
  selector:
    app: hs-box-office
  ports:
    - nodePort: 30099
      port: 9009
      targetPort: 9009
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-box-office
spec:
  selector:
    matchLabels:
      app: hs-box-office
  template:
    metadata:
      labels:
        app: hs-box-office
    spec:
      initContainers:
        - name: liquibase-box
          image: mhws/liquibase-hs-box-office:latest
          imagePullPolicy: Always
          args:
            - --defaults-file=/liquibase/liquibase.properties
            - update
          env:
            - name: LIQUIBASE_COMMAND_URL
              value: "jdbc:postgresql://postgres:5432/db_box_office"
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: HS_BOX_POSTGRES_USERNAME
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: HS_BOX_POSTGRES_PASSWORD
      containers:
        - name: hs-box-office
          image: mhws/hs-box-office:latest
          imagePullPolicy: Always
          args:
            - application.jar
            - --spring.cloud.config.enabled=true
            - --spring.profiles.active=
          ports:
            - containerPort: 9009
          env:
            - name: CONFIGSERVER_URI
              value: "http://hs-config:8888"
            - name: HS_BOX_OFFICE_EUREKA_URI
              value: "http://hs-eureka:8761/eureka"
            - name: HS_BOX_OFFICE_KAFKA_URI
              value: "kafka:29092"
            - name: HS_BOX_OFFICE_DATASOURCE_DATABASE
              value: "db_users"
            - name: HS_BOX_OFFICE_DATASOURCE_HOST
              value: "postgres"
            - name: HS_BOX_OFFICE_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: HS_BOX_POSTGRES_USERNAME
            - name: HS_BOX_OFFICE_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: HS_BOX_POSTGRES_PASSWORD
            - name: HS_BOX_OFFICE_DATASOURCE_PORT
              value: "5432"
      restartPolicy: Always
