apiVersion: v1
kind: Service
metadata:
  labels:
    app: hs-cms
  name: hs-cms
spec:
  type: NodePort
  selector:
    app: hs-cms
  ports:
    - nodePort: 30064
      port: 8764
      targetPort: 8764
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-cms
spec:
  selector:
    matchLabels:
      app: hs-cms
  template:
    metadata:
      labels:
        app: hs-cms
    spec:
      initContainers:
        - name: liquibase-cms
          image: mhws/liquibase-hs-cms:latest
          imagePullPolicy: IfNotPresent
          args:
            - --defaults-file=/liquibase/liquibase.properties
            - update
          env:
            - name: LIQUIBASE_COMMAND_URL
              value: "jdbc:postgresql://postgres:5432/db_cms"
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: HS_CMS_POSTGRES_USERNAME
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: HS_CMS_POSTGRES_PASSWORD
      containers:
        - name: hs-cms
          image: mhws/hs-cms:latest
          imagePullPolicy: IfNotPresent
          args:
            - application.jar
            - --spring.cloud.config.enabled=true
            - --spring.profiles.active=
          ports:
            - containerPort: 8764
          env:
            - name: CONFIGSERVER_URI
              value: "http://hs-config:8888"
            - name: HS_CMS_EUREKA_URI
              value: "http://hs-eureka:8761/eureka"
            - name: HS_CMS_KAFKA_URI
              value: "kafka:29092"
            - name: HS_CMS_HAZELCAST_ADDRESSES
              value: "hazelcast:5701"
            - name: HS_CMS_DATASOURCE_DATABASE
              value: "db_users"
            - name: HS_CMS_DATASOURCE_HOST
              value: "postgres"
            - name: HS_CMS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: HS_CMS_POSTGRES_USERNAME
            - name: HS_CMS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: HS_CMS_POSTGRES_PASSWORD
            - name: HS_CMS_DATASOURCE_PORT
              value: "5432"
      restartPolicy: Always
