apiVersion: v1
kind: Service
metadata:
  labels:
    app: hs-files
  name: hs-files
spec:
  type: NodePort
  selector:
    app: hs-files
  ports:
    - nodePort: 30067
      port: 8767
      targetPort: 8767
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-files
spec:
  selector:
    matchLabels:
      app: hs-files
  template:
    metadata:
      labels:
        app: hs-files
    spec:
      containers:
        - name: hs-files
          image: mhws/hs-files:latest
          imagePullPolicy: IfNotPresent
          args:
            - application.jar
            - --spring.cloud.config.enabled=true
            - --spring.profiles.active=
          ports:
            - containerPort: 8767
          volumeMounts:
            - name: pictures-store
              mountPath: /pictures
          env:
            - name: CONFIGSERVER_URI
              value: "http://hs-config:8888"
            - name: HS_FILES_EUREKA_URI
              value: "http://hs-eureka:8761/eureka"
            - name: HS_FILES_KAFKA_URI
              value: "kafka:29092"
            - name: HS_FILES_HAZELCAST_ADDRESSES
              value: "hazelcast:5701"
      restartPolicy: Always
      volumes:
        - name: pictures-store
          persistentVolumeClaim:
            claimName: files-storage
