apiVersion: v1
kind: Service
metadata:
  labels:
    app: hs-files-compressor
  name: hs-files-compressor
spec:
  type: NodePort
  selector:
    app: hs-files-compressor
  ports:
    - nodePort: 30069
      port: 8769
      targetPort: 8769
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-files-compressor
spec:
  selector:
    matchLabels:
      app: hs-files-compressor
  template:
    metadata:
      labels:
        app: hs-files-compressor
    spec:
      containers:
        - name: hs-files-compressor
          image: mhws/hs-files-compressor:latest
          imagePullPolicy: IfNotPresent
          args:
            - application.jar
            - --spring.cloud.config.enabled=true
            - --spring.profiles.active=
          ports:
            - containerPort: 8769
          volumeMounts:
            - mountPath: /app/paintings
              name: paintings-store
          env:
            - name: CONFIGSERVER_URI
              value: "http://hs-config:8888"
            - name: HS_FILES_COMPRESSOR_EUREKA_URI
              value: "http://hs-eureka:8761/eureka"
            - name: HS_FILES_CLIENT_SERVER_URLS
              value: ws://hs-files:8767/ws
      restartPolicy: Always
      volumes:
        - name: paintings-store
          persistentVolumeClaim:
            claimName: files-storage
