apiVersion: v1
kind: Service
metadata:
  labels:
    app: hs-gateway
  name: hs-gateway
spec:
  type: NodePort
  selector:
    app: hs-gateway
  ports:
    - nodePort: 30000
      port: 8762
      targetPort: 8762
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-gateway
spec:
  selector:
    matchLabels:
      app: hs-gateway
  template:
    metadata:
      labels:
        app: hs-gateway
    spec:
      containers:
        - name: hs-gateway
          image: mhws/hs-gateway:latest
          imagePullPolicy: IfNotPresent
          args:
            - application.jar
            - --spring.cloud.config.enabled=true
            - --spring.profiles.active=
          ports:
            - containerPort: 8762
          env:
            - name: CONFIGSERVER_URI
              value: "http://hs-config:8888"
            - name: HS_GATEWAY_EUREKA_URI
              value: "http://hs-eureka:8761/eureka"
      restartPolicy: Always

