apiVersion: v1
kind: Service
metadata:
  labels:
    app: hs-notifications
  name: hs-notifications
spec:
  type: NodePort
  selector:
    app: hs-notifications
  ports:
    - nodePort: 30079
      port: 8079
      targetPort: 8079
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-notifications
spec:
  selector:
    matchLabels:
      app: hs-notifications
  template:
    metadata:
      labels:
        app: hs-notifications
    spec:
      containers:
        - name: hs-notifications
          image: mhws/hs-notifications:latest
          imagePullPolicy: Always
          args:
            - application.jar
            - --spring.cloud.config.enabled=true
            - --spring.profiles.active=
          ports:
            - containerPort: 8079
          env:
            - name: CONFIGSERVER_URI
              value: "http://hs-config:8888"
            - name: HS_NOTIFICATIONS_EUREKA_URI
              value: "http://hs-eureka:8761/eureka"
            - name: HS_NOTIFICATIONS_KAFKA_URI
              value: "kafka:29092"
            - name: HS_NOTIFICATIONS_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hs-notifications-secrets
                  key: HS_NOTIFICATIONS_MAIL_PASSWORD
      restartPolicy: Always
