server:
  port: 9009

spring:
  r2dbc:
    url: r2dbc:postgresql://${HS_BOX_OFFICE_DATASOURCE_HOST}:${HS_BOX_OFFICE_DATASOURCE_PORT}/${HS_BOX_OFFICE_DATASOURCE_DATABASE}
    username: ${HS_BOX_OFFICE_DATASOURCE_USERNAME}
    password: ${HS_BOX_OFFICE_DATASOURCE_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${HS_BOX_OFFICE_EUREKA_URI:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"

db:
  host: ${HS_BOX_OFFICE_DATASOURCE_HOST}
  port: ${HS_BOX_OFFICE_DATASOURCE_PORT}
  database: ${HS_BOX_OFFICE_DATASOURCE_DATABASE}

management:
  endpoints:
    web:
      exposure:
        include: "*"

# logging:
#   level:
#     org:
#       springframework:
#         security: DEBUG
#         web: DEBUG
#       hibernate: ERROR
