server:
  port: 8769

app:
  paintings:
    repository:
      fs:
        mount: ${HS_FILES_PAINTINGS_VOLUME:./paintings}
    client:
      server-urls: ${HS_FILES_CLIENT_SERVER_URLS:ws://localhost:8767/ws}
