services:
  eureka:
    image: ${HS_EUREKA_IMAGE}
    ports:
      - ${HS_EUREKA_PORT:-8761}:8761

  gateway-gradle:
    profiles: ["from-gradle"]
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - ${HS_GATEWAY_PORT:-8762}:8762
    environment:
      EUREKA_URI: ${HS_GATEWAY_EUREKA_URI:-http://eureka:8761/eureka}

  gateway-jar:
    profiles: ["from-jar"]
    build:
      context: .
      dockerfile: from-jar.dockerfile
    ports:
      - ${HS_GATEWAY_PORT:-8762}:8762
    environment:
      EUREKA_URI: ${HS_GATEWAY_EUREKA_URI:-http://eureka:8761/eureka}

