apiVersion: v1
kind: Service
metadata:
  labels:
    app: hs-eureka
  name: hs-eureka
spec:
  type: NodePort
  selector:
    app: hs-eureka
  ports:
    - nodePort: 30061
      port: 8761
      targetPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-eureka
spec:
  selector:
    matchLabels:
      app: hs-eureka
  template:
    metadata:
      labels:
        app: hs-eureka
    spec:
      containers:
        - name: hs-eureka
          image: mhws/hs-eureka:latest
          imagePullPolicy: Always
          args:
            - application.jar
            - --spring.cloud.config.enabled=true
            - --spring.profiles.active=
          ports:
            - containerPort: 8761
          env:
            - name: CONFIGSERVER_URI
              value: http://hs-config:8888
          livenessProbe:
            httpGet:
              port: 8761
              path: /actuator/health
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 60
      restartPolicy: Always
