apiVersion: v1
kind: Service
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  selector:
    service: zookeeper
  ports:
    - port: 22000
      targetPort: 22000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      service: zookeeper
  template:
    metadata:
      labels:
        service: zookeeper
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      enableServiceLinks: false
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.3.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 22000
          volumeMounts:
            - mountPath: /var/lib/zookeeper/data
              name: zookeeper-data
          resources: { }
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "22000"
            - name: ZOOKEEPER_DATA_DIR
              value: "/var/lib/zookeeper/data"
          livenessProbe:
            exec:
              command:
                - nc -z localhost 22000 || exit -1
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 60
      hostname: zookeeper
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi
