apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-data
data:
  01_init_users.sh: |
    #!/usr/bin/env bash

    HS_USERNAME=$HS_USER_POSTGRES_USERNAME
    HS_PASSWORD=$HS_USER_POSTGRES_PASSWORD
    HS_DATABASE=$HS_USER_POSTGRES_DATABASE

    psql --username "postgres" --dbname "postgres" <<-EOSQL
      CREATE USER $HS_USERNAME WITH PASSWORD '$HS_PASSWORD';
    EOSQL

    psql --username "postgres" --dbname "postgres" <<-EOSQL
    	CREATE DATABASE $HS_DATABASE;
      GRANT ALL PRIVILEGES ON DATABASE $HS_DATABASE TO $HS_USERNAME;
    EOSQL

    psql --username "postgres" --dbname "$HS_DATABASE" <<-EOSQL
        GRANT USAGE, CREATE ON SCHEMA public TO $HS_USERNAME;
    EOSQL
  02_init_cms.sh: |
    #!/usr/bin/env bash

    set -e

    HS_USERNAME=$HS_CMS_POSTGRES_USERNAME
    HS_PASSWORD=$HS_CMS_POSTGRES_PASSWORD
    HS_DATABASE=$HS_CMS_POSTGRES_DATABASE

    psql --username "postgres" --dbname "postgres" <<-EOSQL
      CREATE USER $HS_USERNAME WITH PASSWORD '$HS_PASSWORD';
    EOSQL

    psql --username "postgres" --dbname "postgres" <<-EOSQL
    	CREATE DATABASE $HS_DATABASE;
      GRANT ALL PRIVILEGES ON DATABASE $HS_DATABASE TO $HS_USERNAME;
    EOSQL

    psql --username "postgres" --dbname "$HS_DATABASE" <<-EOSQL
        GRANT USAGE, CREATE ON SCHEMA public TO $HS_USERNAME;
    EOSQL
  03_init_box.sh: |
    #!/usr/bin/env bash

    set -e

    HS_USERNAME=$HS_BOX_POSTGRES_USERNAME
    HS_PASSWORD=$HS_BOX_POSTGRES_PASSWORD
    HS_DATABASE=$HS_BOX_POSTGRES_DATABASE

    psql --username "postgres" --dbname "postgres" <<-EOSQL
      CREATE USER $HS_USERNAME WITH PASSWORD '$HS_PASSWORD';
    EOSQL

    psql --username "postgres" --dbname "postgres" <<-EOSQL
        CREATE DATABASE $HS_DATABASE;
      GRANT ALL PRIVILEGES ON DATABASE $HS_DATABASE TO $HS_USERNAME;
    EOSQL

    psql --username "postgres" --dbname "$HS_DATABASE" <<-EOSQL
        GRANT USAGE, CREATE ON SCHEMA public TO $HS_USERNAME;
    EOSQL
