apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  clusterIP: None
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.0-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-entrypoint
              mountPath: /docker-entrypoint-initdb.d/
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: postgres-secrets
          env:
            - name: HS_USER_POSTGRES_DATABASE
              value: "db_users"
            - name: HS_CMS_POSTGRES_DATABASE
              value: "db_cms"
            - name: HS_BOX_POSTGRES_DATABASE
              value: "db_box_office"
      volumes:
        - name: postgres-entrypoint
          configMap:
            name: postgres-init-data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi
