apiVersion: v1
kind: Service
metadata:
  labels:
    app: hazelcast-ui
  name: hazelcast-ui
spec:
  type: NodePort
  selector:
    app: hazelcast-ui
  ports:
    - nodePort: 30080
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hazelcast-ui-storage
  labels:
    app: hazelcast-ui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hazelcast-ui
  labels:
    app: hazelcast-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hazelcast-ui
  template:
    metadata:
      labels:
        app: hazelcast-ui
    spec:
      containers:
        - name: hazelcast-ui
          image: hazelcast/management-center:5.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: hazelcast-ui-config
              mountPath: /opt/hazelcast/ext/config
            - name: hazelcast-ui-storage
              mountPath: /opt/hazelcast/ext/data
          env:
            - name: MC_INIT_CMD
              value: >
                ./bin/mc-conf.sh cluster add
                --lenient=true
                -H /opt/hazelcast/ext/data
                -cc /opt/hazelcast/ext/config/hazelcast-client.yml;
            - name: JAVA_OPTS
              value: >
                -Dhazelcast.mc.healthCheck.enable=true
                -Dhazelcast.mc.tls.enabled=false
      restartPolicy: Always
      volumes:
        - name: hazelcast-ui-config
          configMap:
            name: hazelcast-config-data
        - name: hazelcast-ui-storage
          persistentVolumeClaim:
            claimName: hazelcast-ui-storage
