apiVersion: v1
kind: Service
metadata:
  labels:
    app: hazelcast-ui
  name: hazelcast-ui
spec:
  type: NodePort
  selector:
    app: hazelcast-ui
  ports:
    - nodePort: 30080
      port: 8080
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hazelcast-ui
  labels:
    app: hazelcast-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hazelcast-ui
  template:
    metadata:
      labels:
        app: hazelcast-ui
    spec:
      containers:
        - name: hazelcast-ui
          image: hazelcast/management-center:5.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
