apiVersion: v1
kind: Service
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hazelcast
  ports:
    - port: 5701
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
spec:
  selector:
    matchLabels:
      app: hazelcast
  serviceName: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
        - name: hazelcast
          image: hazelcast/hazelcast:5.3.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5701
              name: hazelcast
              protocol: TCP
          volumeMounts:
            - name: hazelcast-config
              mountPath: /opt/hazelcast/config_ext/
          env:
            - name: JAVA_OPTS
              value: >
                -Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yml
                -Dhz.jet.enabled=true
                -Dhazelcast.shutdownhook.policy=GRACEFUL
                -Dhazelcast.shutdownhook.enabled=true
                -Dhazelcast.graceful.shutdown.max.wait=600
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          readinessProbe:
            httpGet:
              path: /hazelcast/health/ready
              port: 5701
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5701
              scheme: HTTP
      volumes:
        - name: hazelcast-config
          configMap:
            name: hazelcast-config-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
