name: Main

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: deploy

    steps:
      - name: Run SSH commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          username: art
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |-
            cd ~/hs
            git fetch --all
            git reset --hard ${{ github.sha }}
            sudo docker compose up -d
          script_stop: true
